runtime: custom        # Usas contenedor personalizado
env: flex              # App Engine Flexible environment

service: backend-service  

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

entrypoint: ""         # La imagen Docker define su propio CMD o ENTRYPOINT

# ✅ Variables de entorno (añádelas aquí)
env_variables:
  DB_USER: "admin"
  DB_PASS: "Cafe2020"
  DB_CLUSTER: "cluster0.9pawl.mongodb.net"
  DB_NAME: "dbtest"
  DB_SERV: "mongodb+srv://"
  NODE_ENV: "production"
