steps:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    secretEnv: ['TOKEN_SONRQUBE_GITOPS_GLOBAL']
    args:
      - '-c'
      - |
        echo "Ejecutando análisis SonarQube..."
        mvn sonar:sonar \
          -Dsonar.projectKey=my-service-dev \
          -Dsonar.host.url=https://sonarqube.mycompany.com \
          -Dsonar.login=$TOKEN_SONRQUBE_GITOPS_GLOBAL

availableSecrets:
  secretManager:
    - versionName: projects/fiery-synthesis-472821-m2/secrets/TOKEN_SONRQUBE_GITOPS_GLOBAL/versions/latest
      env: 'TOKEN_SONRQUBE_GITOPS_GLOBAL'
