steps:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    secretEnv: ['TOKEN_SONRQUBE_GITOPS']
    args:
      - '-c'
      - |
        mvn sonar:sonar \
          -Dsonar.projectKey=my-service-dev \
          -Dsonar.host.url=https://sonarqube.mycompany.com \
          -Dsonar.login=${TOKEN_SONRQUBE_GITOPS}

availableSecrets:
  secretManager:
    - versionName: projects/fiery-synthesis-472821-m2/secrets/TOKEN_SONRQUBE_GITOPS/versions/latest
      env: 'TOKEN_SONRQUBE_GITOPS'