steps:
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    secretEnv: ['TOKEN_SONRQUBE_GITOPS']
    args:
      - '-c'
      - |
        echo "✅ Verificando acceso al secreto TOKEN_SONRQUBE_GITOPS"
        if [ -z "$TOKEN_SONRQUBE_GITOPS" ]; then
          echo "❌ ERROR: El secreto NO está disponible"
          exit 1
        else
          echo "✅ Secreto disponible (valor oculto por seguridad)"
          echo "${TOKEN_SONRQUBE_GITOPS:0:4}********" # muestra solo los 4 primeros chars
        fi