apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2
  namespace: preproduction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: node-app2
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: node-app
        image: hakimsamouh/gitops:v-0.0.5
        ports:
        - containerPort: 7000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

