apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: node-app2
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
<<<<<<< HEAD:deployment-app.yaml
      - name: node-app
=======
      - name: azure-vote-front
>>>>>>> 06936f547d8e1dcbddd9fdd086d140736563a4d6:iainfracvsp.yaml
        image: hakimsamouh/node-app:v0.0.0
        ports:
        - containerPort: 7000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

