apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-manager-producto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-manager-producto
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: api-manager-producto
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: api-manager-producto
        image: hakimsamouh/gitops:v-0.0.0
        ports:
        - containerPort: 7000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

