apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: node-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: node-app
        image: hakimsamouh/node-web-app:v1.0.0
        ports:
        - containerPort: 7000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

