name: CI/CD to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Instalar Node y dependencias
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
          
        run: |
         cd $GITHUB_WORKSPACE
         ls -la
         npm install
      - name: Run tests
        run: npm test

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 3️⃣ Configurar gcloud con service account
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
         credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
         project_id: ${{ secrets.GCP_PROJECT }}
         install_components: 'cloud-build-local'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
         credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
         project_id: ${{ secrets.GCP_PROJECT }}
         install_components: 'cloud-build-local'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
         credentials_json: ${{ secrets.GCP_SA_KEY }}

