name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - run: npm install express
      - run: npm install mongose
      - run: ls -l 
      - run: echo "let s go cwith github Actions"
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku HEROKU_APP
          heroku_email: ${{secrets.TOCKEN_HEROKU}}