name: Deployment pipeline
on:
 push:
  branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Express   
      - run: npm install express
      - name: Install mongose
      - run: npm install mongose
      - name: Listar directory app
      - run: ls -l 
      - name: build
      - run: npm run build 
      - name: Test
      - run: npm test